"""add profile_picture_file_object_id to users

Revision ID: 16f1f5986188
Revises: 
Create Date: 2026-03-23 15:32:28.395088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f1f5986188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_file_object_id', sa.UUID(), nullable=True))
    op.create_index('ix_users_profile_picture_file_object_id', 'users', ['profile_picture_file_object_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['profile_picture_file_object_id'])
    op.create_foreign_key(None, 'users', 'file_objects', ['profile_picture_file_object_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_profile_picture_file_object_id', table_name='users')
    op.drop_column('users', 'profile_picture_file_object_id')
    # ### end Alembic commands ###
