"""Add email column to otp_sessions

Revision ID: 1eea25fea76d
Revises: 
Create Date: 2026-03-18 14:10:53.661425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eea25fea76d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_sessions', sa.Column('email', sa.String(length=20), nullable=True))
    op.alter_column('otp_sessions', 'phone_e164',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('return_zones', sa.Column('buffer_radius_m', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('return_zones', 'buffer_radius_m')
    op.alter_column('otp_sessions', 'phone_e164',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('otp_sessions', 'email')
    # ### end Alembic commands ###
